### ISSUE TITLE
Jupysql silently swallows exceptions when duckdb returns a negative interval

### ISSUE THREAD

**Issue by maartenbosteels** [ploomber/sql#106]
Jupysql silently swallows exceptions, I think. (edited) 

```
import duckdb 
db = duckdb.connect()
db.sql("select age(TIMESTAMP '2020-12-25', TIMESTAMP '2020-12-26') age")
┌──────────┐
│   age    │
│ interval │
|──────────┤
│ -1 days  │
└──────────┘
```

But with jupysql, the same query:

`%sql select age(TIMESTAMP '2020-12-25', TIMESTAMP '2020-12-26') age`
shows:
```
+-----+
| age |
+-----+
+-----+

```

So, I see two issues:
* jupysql cannot deal with negative intervals
* jupysql shows an empty resultset when something goes wrong.

The latter is rather dangerous. In the example above it's quite obvious that there should be one row in the output, but for more complex queries an empty result can lead to completely wrong conclusions. (edited)

**Comment by edublancas** [comment]
this is with duckdb, right?

**Comment by maartenbosteels** [comment]
Yes, it's in the title ;-)

**Comment by neelasha23** [comment]
This looks like an issue with `duckdb-engine`. PFB the results:

`Postgres` (both JupySQL and Sqlalchemy)

<img width="1059" alt="Screenshot 2023-11-06 at 2 18 47 PM" src="https://github.com/ploomber/sql/assets/29096135/46228ea3-d036-448d-b437-cd717dab6242">

`duckdb-engine`

<img width="855" alt="Screenshot 2023-11-06 at 2 20 33 PM" src="https://github.com/ploomber/sql/assets/29096135/3628ea76-02de-48b7-a6e6-6150141764b0">

@edublancas

**Comment by maartenbosteels** [comment]
I see.
But wouldn't jupysql be able to catch the exception and show it to the user, instead of showing an ampty result set?

**Comment by neelasha23** [comment]
I debugged the code and it looks like the exception is being handled in `sqlqlchemy` itself, and it returns an empty result set to JupySQL.
Stacktrace:
```
 1075     self,
   1076     result: CursorResult[Any],
   1077     dbapi_cursor: Optional[DBAPICursor],
   1078     err: BaseException,
   1079 ) -> NoReturn:
-> 1080     result.connection._handle_dbapi_exception(
   1081         err, None, None, dbapi_cursor, result.context
   1082     )

File ~/miniforge3/envs/jupysql_sqlalchemy/lib/python3.10/site-packages/sqlalchemy/engine/base.py:2346, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context, is_sub_exec)
   2344     else:
   2345         assert exc_info[1] is not None
-> 2346         raise exc_info[1].with_traceback(exc_info[2])
   2347 finally:
   2348     del self._reentrant_error

File ~/miniforge3/envs/jupysql_sqlalchemy/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py:1135, in CursorFetchStrategy.fetchall(self, result, dbapi_cursor)
   1129 def fetchall(
   1130     self,
   1131     result: CursorResult[Any],
   1132     dbapi_cursor: DBAPICursor,
   1133 ) -> Any:
   1134     try:
-> 1135         rows = dbapi_cursor.fetchall()
   1136         result._soft_close()
   1137         return rows

OverflowError: Python int too large to convert to C int
```

**Comment by edublancas** [comment]
@neelasha23 sounds good, please update us when you have more information

**Comment by edublancas** [comment]
@neelasha23 I'm confused about this.

based on what I read, this is what I understood.

- if we run this on duckdb using a native connection, this works fine
- if we run this on duckdb-engine, this breaks

if the above statements are true. it seems like we should open an issue in the duckdb-engine, since this is not a jupysql issue.

**Comment by neelasha23** [comment]
Yes I feel the same.
But currently JupySQL is not rethrowing the same exception instead printing empty results. this is because we have a `try catch` as I pointed out in the PR. Should we just ignore it and open an issue in duckdb-engine?

**Comment by edublancas** [comment]
can you point me to the problematic `try catch` in our codebase?

**Comment by neelasha23** [comment]
I have added details in [this comment](https://github.com/ploomber/jupysql/pull/937#issuecomment-1799313715)

@edublancas

**Comment by maartenbosteels** [comment]
Similar issue:
https://github.com/ploomber/sql/issues/107

**Comment by edublancas** [comment]
@neelasha23 ok, I looked at this [comment](https://github.com/ploomber/jupysql/pull/937#issuecomment-1799313715)

I added such `try except` because I found that queries that didn't return results (eg `create table`) would break when calling `.keys()`.

However, I'm catching all exceptions, which now showed to be problematic because there's >1 reason why an exception would raise there (one being an empty result, another being, an error in the db, as we just found out).

Let's see if we can more accurately catch the scenario where the db returns empty results (but there is no error). we can add an integration test across several dbs to ensure this is compatible with the most important dbs. if that works, great. if not, we can think of other solutions.
