### ISSUE TITLE
Write tutorial for Advanced aggregation operations in SQL

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#35]
Task 
Write tutorial for Advanced aggregation operations in SQL

Starter file

[Advanced aggregation operations in SQL](https://ploomber-sql.readthedocs.io/en/latest/advanced-querying-techniques/advanced-aggregations.html)

Use existing scripts to download data, use db with multiple tables

**Comment by lfunderburk** [comment]
Hi @TegveerG 

Please share here what functions and operations you want to introduce in this tutorial

If you have a few in the works already, please list them here.

**Comment by TegveerG** [comment]
Operations and overall structure of the tutorial is as follows:

1. I do have the same code from loading the data + engine etc, shall condense those sections 
2. Ranking - Use of `RANK()` in terms of its general syntax, examples, and a medium level exercise question. I also introduce partitioning within ranking
3. Windowing - Mainly diving into frame selection (`preceding`, `following`, `unbounded ...`), using aggregate functions in it, and a hard exercise question
4. Pivoting - `PIVOT` is mainly supported by DuckDB and, due to this, I also show how `CASE WHEN` can be used to obtain the same results. An easier exercise question is included
5. Rollups -  thinking whether to add this section or not. The longest docs in the repo span up to 300 code lines, with this section this doc can go till 400. Only this section is left to be completed, but I can push a PR for now @lfunderburk
